// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pogdidpajhaszpegtjrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZ2RpZHBhamhhc3pwZWd0anJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NDk0NDAsImV4cCI6MjA2MjMyNTQ0MH0.q_cmDkBDpjvn-FBb_OuCIBgBit3lqF595DFX_p7fp-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);