
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oidugjvyllxoguhekame.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZHVnanZ5bGx4b2d1aGVrYW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjgzODksImV4cCI6MjA2MjUwNDM4OX0.dtlEJ5QBhQpPIb6584Lku7rjb5xpOnMVul3KRuvTtcA";

// Configure the Supabase client with explicit auth settings and storage
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-application-name': 'eventify',
    },
  },
});
